
services:

  bingo:
    image: antonsiomchen/cheminfo-db:postgres16.13-bingo1.40.0
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 1024mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    # volumes:
    #   - db_data:/var/lib/postgresql/data
  rdkit:
    image: antonsiomchen/cheminfo-db:postgres18.3-rdkit2025.09.6
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: example



# volumes:
#   db_data: