site_name: "ChemSchema"
site_description: "A set of tools for handling chemical data in databases and data science workflows"
repo_url: "https://github.com/asiomchen/chemschema"
repo_name: "asiomchen/chemschema"
copyright: Copyright 2025

use_directory_urls: true
docs_dir: "docs"



theme: 
  name: material
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/lightbulb-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: green
    accent: green
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: green
    accent: green
    toggle:
      icon: material/lightbulb-outline
      name: Switch to system preference
  features:
  - content.code.annotate
  - content.code.copy
  # - content.code.select
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  # - navigation.instant.preview
  - navigation.instant.progress
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow

extra_javascript:
    - assets/js/readthedocs.js

extra_css:
  - assets/css/tweak-width.css
  - assets/css/custom-chemschema.css

watch:
  - "src"

plugins:
  - search
  - autorefs
  - social
  # Other plugin
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
          inventories:
            - https://docs.python.org/objects.inv
            - https://www.rdkit.org/docs/objects.inv
            - http://docs.sqlalchemy.org/en/stable/objects.inv
  # - mkdocs-jupyter:
  #     execute: false
  #     include: ["*.ipynb"]

nav:
  - ChemSchema: index.md
  - API:
    - chemschema.bingo:
        - bingo.types: api/bingo/types.md
        - bingo.functions: api/bingo/functions.md
        - bingo.index: api/bingo/db_index.md
    - chemschema.rdkit:
        - rdkit.types: api/rdkit/types.md
        - rdkit.functions: api/rdkit/functions.md
        - rdkit.index: api/rdkit/db_index.md

  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/asiomchen/chemschema
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/anton-siomchen/
  - icon: fontawesome/brands/docker
    link: https://hub.docker.com/
  